### PR TITLE
Location selector improvements (Take 2)

### PR DESCRIPTION
**Pull request by martindevans**
I've branched out the code you're likely to want to merge, so this time I won't inadvertently break the entire application whilst trying to submit a relatively minor PR!
- Removed restriction to only browse in program files
- When mods are successfully loaded the selected path is saved in a file (in appdata). When the application starts again the saved path is prepopulated into the field
- Refactored `void UpdatedLocation()` to `Task<Library> LoadLibrary(string path)`, this method has less side effects now.
- Simplified form close handling. If the form closes the application closes - when the form used to be closed (after clicking the continue button) it is instead _hidden_.
- Pulled some strings out from inline to be defined in the resources file

### CODE REVIEW

**Comment by martindevans** [comment]
I'm not sure why that CI build failed :S

Travis says:

> CSC: error CS2001: Source file `Models/PlaceRoute/Searchspace.cs' could not be found

But if you browse the commit (I copied this URL directly from travis, so it's definitely the right one) you can see the file right [here](https://github.com/thexa4/FactorioCalculator/tree/967efec45f4f04ac20861f4027c74728ce1ff628/FactorioCalculator/Models/PlaceRoute)!

Not too sure how to proceed :/

**Comment by thexa4** [comment]
It seems to look for Models/PlaceRoute/Searchspace.cs while the file is named Models/PlaceRoute/SearchSpace.cs (the CI is linux based and thus case-sensitive)

I'll have time to look at the changes tomorrow.

**Comment by thexa4** [comment]
It seems to be my mistake, don't worry about the non-passing build.

**Comment by thexa4** [comment]
Thanks for the pull request, I merged your changes with a few minor changes on things that happen when the user selects a wrong directory.

I noticed you removed a lot of code in your fork, what are your plans for it? The treeviewer looks cool by the way.

**Comment by martindevans** [comment]
My initial plan was just a quick and dirty hack to view the total recipe tree (like I already have).

I'm vaguely considering developing a new recipe solver to calculate optimal assembler ratios - it sounds like a fun technical challenge!

**Comment by thexa4** [comment]
You need a constraint solver for it, doing it greedily won't work for recipes with oil. Have fun :)

**Comment by martindevans** [comment]
Presumably it doesn't work for oil because oil processing has multiple outputs which messes up other branches of the recipe tree?

**Comment by thexa4** [comment]
Correct, some processes produce waste output which you need to convert back into usable stuff. My attempts before the solver never resulted in optimal solutions.

**Pull request merged**
